#HalfminerSystem Config
command:
  home:
    #Time until /home will be blocked
    timeUntilHomeBlockMinutes: 15
  neutp:
    #Bounds in which the generated position will lie in
    boundMin: 1000
    boundMax: 10000
  verkauf:
    #Base amount for 1 HalfCoin
    beetroot: 30
    brownmushroom: 20
    cactus: 110
    carrot: 30
    cocoa: 45
    melon: 110
    netherwart: 40
    potato: 30
    pumpkin: 40
    redmushroom: 30
    sugarcane: 55
    wheat: 25
  vote:
    #Command to run when a player has voted
    voteRewardCommand: vt run casino:dropcase %PLAYER%
    #Amount of votes until command execution
    threshold: 2000
    #Command to execute when threshold has been met
    commandToExecute: mail send Kakifrucht Event ankuendigen, votes erreicht
handler:
  storage:
    #Time in minutes the storage will be autosaving
    autoSaveMinutes: 15
  teleport:
    #Time in seconds players cannot move before being teleported
    cooldownSeconds: 3
antiKillfarming:
  #Time in seconds the primary block will be, this doubles every block
  blockTime: 300
  #Length of killstreak until blocked
  thresholdUntilBlock: 5
  #Amount of seconds until the killstreak is reset
  thresholdUntilRemoval: 100
  #List of commands that are still allowed
  killfarmingCommandExemptions:
  - 'regeln'
  - 'hilfe'
  - 'warn'
  - 'ban'
  - 'tempban'
  - 'bminfo'
antiXray:
  #Time until a counted player won't be counter anymore
  intervalUntilClearSeconds: 600
  #Amount of protected blocks that have to be broken in given time frame until warning
  protectedBlockThreshold: 10
  #How many non protected blocks should be broken per protected block
  protectedBlockRatioThreshold: 15
  #Protected blocks / materials
  protectedBlocks:
  - DIAMOND_ORE
  - EMERALD_ORE
  - GOLD_ORE
  - REDSTONE_ORE
autoMessage:
  #Time between each message
  intervalSeconds: 240
  messages:
  - 'Set messages here'
chat:
  #Add formats to the list, you need the permission node hms.chat.format.name
  #hms.chat.topformat always grants top format (which has highest priority)
  formats:
  - 'owner:%PREFIX% &r- &l%PLAYER%%SUFFIX%: &7%MESSAGE%'
  - 'default:%PREFIX% &r- %PLAYER%: &7%MESSAGE%'
combatLog:
  #Broadcast when a player logs out
  broadcastLog: true
  #Time in seconds until untag
  tagTime: 15
motd:
  #Minimum shown slot count
  playerCountThreshold: 50
  #Minimum amount of slots that will be free
  #Example: Buffer is 5, threshold is 50, when 45 players
  #are online, it will show 45/50. If 46 players are online
  #the it will show 46/51, due to the buffer of 5 players.
  #63 players online would show 63/68.
  playerCountBuffer: 5
  #Colors that will be used to replace the placeholder %COLOR% with
  randomColors:
  - 2
  - 3
  - 6
  - 9
  - b
performance:
  #Delay in ticks until the blocks will be lifted
  ticksDelayUntilClear: 160
  #Number in events until redstone will be blocked, ticksDelayUntilClear clears this
  howMuchRedstoneAllowed: 32
  #How many pistons are allowed to extend or retract, ticksDelayUntilClear clears this
  howManyPistonsAllowed: 400
  #How many hoppers are allowed
  hopperLimit: 64
  #Radius around hopper that will be checked, changing this value may introduce lag
  hopperLimitRadius: 7
  #Log to console if a limit has been hit
  hopperLimitLog: false
  #How many living entities are allowed to be around a new mobspawner spawned entity
  entitiyLimitLiving: 100
  #How many entities of the spawned type are allowed to be around a new mobspawner spawned entity
  entityLimitSame: 25
  #Entity limit box radius, that will be checked on mobspawn from a spawner
  boxSize: 16
respawn:
  #Command to be run on first player join, supports %PLAYER% placeholder
  firstJoinCommand: ''
skillLevel:
  #Level that has to be reached for a derank to occur
  derankThreshold: 16
  #Time until a player will be deranked when he didn't fight in the meantime
  timeUntilDerankDays: 4
  #Amount of elo points the player will lose on derank
  derankLossAmount: 250
  #Time in minutes until a kill will be counted again towards elo after a kill
  timeUntilKillCountAgainMinutes: 10
  #Six skillgroups need to be set, first character is the color code
  #Upper level in the list are the top levels
  skillGroups:
  - 0Pro
  - aEmerald
  - bDiamant
  - 6Gold
  - 8Eisen
  - 7Noob
tps:
  #The higher, the more precise, however the tps will update slower
  ticksBetweenUpdate: 100
  #If set higher, the tps will update more slowly due to more values that are taken into consideration
  historySize: 6
  #If the tps falls under this tps, players with notify permission will be notified
  alertThreshold: 17.0
localization:
  consoleName: 'Konsole'
  lineSeparator: '&e&m------------------------------------------------\n'
  noPermission: '&cDu hast nicht die Berechtigung dies zu verwenden'
  notAPlayer: 'Dieses Kommando kann nur als Spieler ausgefuehrt werden'
  playerDoesNotExist: '&cDieser Spieler existiert nicht'
  playerNotOnline: '&cDieser Spieler ist nicht online'
  prefix: '&7%PREFIX% &e>>&r '
  commandChatAll: 'alle'
  commandChatBossbar: '&7Bossbar an &e%SENDTO% &7fuer &a%TIME% Sekunden &7versendet, Nachricht: &r%MESSAGE%'
  commandChatCleared: '&7Der Chat wurde von &e%PLAYER% &7geleert'
  commandChatClearedLog: '%PLAYER% hat den Chat geleert'
  commandChatCountdownStarted: '&7Countdown fuer &e%COUNT% &7Sekunden gestartet'
  commandChatCountdown: 'Countdown: &2&l%COUNT%'
  commandChatMessageSet: '&aNachricht gesetzt zu:&r\n%MESSAGE%'
  commandChatMessageNotSet: '&cEs ist keine Nachricht gesetzt, verwende &f/c set [Nachricht]'
  commandChatNewsSetTo: '&aNachricht als News gesetzt'
  commandChatSend: '&7Deine Nachricht wurde an %SENDTO% versendet'
  commandChatUsage: '&cVerwendung:\n&f/c clear --> Chat leeren\n/c countdown <Zeit> --> Countdown starten\n/c globalmute --> Globalmute umschalten\n/c set [Nachricht] --> Definiere deine Nachricht\n/c title [Zeit] [Spieler] --> Zeige die Nachricht als Titel\n/c bossbar [Zeit] [Spieler] [Farbe] --> Nachricht in BossBar\n/c news --> Setze Nachricht als Servernews\n/c send [Spieler] --> Schicke deine Nachricht'
  commandChatTitle: '&7Titel an &e%SENDTO% &7fuer &a%TIME% Sekunden &7versendet, Nachricht: &r%MESSAGE%'
  commandHmsConfigReloaded: '&aKonfiguration neugeladen'
  commandHmsHomeblockRemove: '&a%PLAYER% &7kann jetzt /home benutzen'
  commandHmsMotdFailed: '&cVerwendung: &f/hms setmotd <motd>'
  commandHmsMotdUpdated: '&7Die MOTD wurde geaendert zu: &r&7%NEWMOTD%'
  commandHmsRenameDone: '&aDer Gegenstand wurde umbenannt in &r"%NAME%&r"'
  commandHmsRenameFailed: '&cHalte den Gegenstand, den du umbenennen willst in deiner Hand'
  commandHmsRingMessage: '&e%PLAYER% &cklingelt dich an, bitte antworte ihm'
  commandHmsRingSent: '&a%PLAYER% wurde angeklingelt'
  commandHmsRingTitle: '&cDu wirst angeklingelt\nBitte antworte %PLAYER%'
  commandHmsSearchhomesNoneFound: '&cEs wurden keine Homes gefunden'
  commandHmsSearchhomesResults: '&7%PLAYER% &e>> &a%HOMENAME%'
  commandHmsSearchhomesStarted: '&7Die Suche nach Homes in einem Radius von &e%RADIUS% &7Bloecken wurde gestartet...'
  commandHmsSkillUsage: '&cVerwendung: &f/hms updateskill <spieler> [modifier]'
  commandHmsSkillUpdated: '&7Das Skilllevel von &e%PLAYER% &7wurde auf Level &e%SKILLLEVEL% &7(&o%OLDELO% &7-> &o%NEWELO%&7) gesetzt'
  commandHmsUsage: '&cVerwendung: &f/hms reload, rename <name> [-lore line1|line2|..], updateskill <spieler>, rmhomeblock <spieler>, ring <spieler>, searchhomes [radius]'
  commandHmstoreGet: '&7Der Wert &o%PATH% &7lautet: &r%VALUE%'
  commandHmstoreRemove: '&7Der Wert &o%PATH% &7wurde entfernt'
  commandHmstoreSave: '&7Die Variablen wurden gespeichert'
  commandHmstoreSet: '&7Der Wert &o%PATH% &7wurde gesetzt zu &r%VALUE%'
  commandHmstoreSetError: '&7Die Eingabe ist ungueltig, der Wert wurde nicht gesetzt'
  commandHmstoreUsage: '&cVerwendung: &f/hmstore get/set/setint/setbool/setdouble/remove/save <path> [value]'
  commandHomeDenied: '&dHallo %PLAYER%, du spielst bereits seit ueber 15 Minuten und hast noch nicht gevoted. Bitte verwende &6&l/vote&d, um wieder Zugriff auf &o/home &dzu erhalten. Voting ist wichtig damit der Server immer schoen gefuellt und somit am Leben bleibt. Als Dankeschoen erhaelst du zudem 2 Votekisten'
  commandHomeDeniedLog: 'Home: %PLAYER% wurde /home verweigert'
  commandLagPlayerInfo: '&7Latenz von %PLAYER%: %LATENCY% &7ms (niedriger ist besser)'
  commandLagPlayerLag: '&cDeine Verbindung ist instabil &a(Server ist stabil)'
  commandLagServerInfo: '&7Server Zustand: %TPS%&7/20.0 TPS'
  commandLagServerLag: '&cDer Server ist sehr instabil, das Team arbeitet daran'
  commandLagServerUnstable: '&eDer Server ist etwas instabil, das Team arbeitet daran'
  commandLagStable: '&aDie Verbindung ist stabil'
  commandNeutpAlreadyUsed: '&cDu kannst diesen Befehl nur einmal verwenden'
  commandNeutpBossbar: 'Lies das Handbuch um mehr über den Server zu erfahren'
  commandNeutpDocumentation: '&7Es wurde ein automatischer Homepunkt angelegt (&e/home&7). Du kannst einen neuen mit &e/sethome&7 setzen. Alle Kommandos unter &e/hilfe&7.'
  commandNeutpLog: 'Neutp: %PLAYER% wurde zu %LOCATION% teleportiert'
  commandNeutpStart: '&aDu wirst an einen eigenen Ort teleportiert'
  commandNeutpTpDone: '&e&lViel Spass auf halfminer.de, %PLAYER%!'
  commandSigneditCopy: '&7Klicke das Schild, welches du kopieren moechtest, erstelle &e%AMOUNT% &7Kopien'
  commandSigneditSet: '&7Klicke ein Schild, um Zeile &e%LINE% &7zu ''&r%TEXT%&7'' zu aendern'
  commandSigneditUsage: '&cVerwendung: &f/signedit copy [anzahl], /signedit <zeile> [text]'
  commandSpawnOthers: '&e%PLAYER% &7wurde teleportiert'
  commandSpawnOthersOfflineAdd: '&e%PLAYER% &7wird beim naechsten Login zum Spawn teleportiert'
  commandSpawnOthersOfflineRemove: '&e%PLAYER% &7wird beim naechsten Login nicht zum Spawn teleportiert'
  commandSpawnSet: '&aSpawnpunkt wurde gesetzt'
  commandStatsCompareInfo: '&7Verwende &e/stats %PLAYER% compare &7zum vergleichen'
  commandStatsCompareLegend: '&7Dein Wert ist &ahoeher&7, Werte sind &egleich&7, dein Wert ist &cgeringer'
  commandStatsOldnames: '&fAlte Namen: &e%OLDNAMES%'
  commandStatsShow: '&3Statistiken fuer %PLAYER% &e>>\n&rSkillgruppe: &e%SKILLGROUP% &7| &rSkilllevel: &e%SKILLLEVEL%&7&o/22\n&rZeit Online: &e%ONLINETIME% &7Minuten | &rGeld: &e%REVENUE% &7HCs verdient\n&rKills: &e%KILLS% &7Mord(e) | &rDeaths: &e%DEATHS% &7Tod(e) | &rK/D: &e%KDRATIO%\n&rGevotet: &e%VOTES% &7mal | &rMobs: &e%MOBKILLS% &7Mobs getoetet\n&rBloecke: &e%BLOCKSPLACED% &7platziert | &e%BLOCKSBROKEN% &7gebrochen'
  commandStatsShowotherStats: '&7Statistiken zu anderen Spielern: &e/stats [Spieler]'
  commandStatsTop: '&e&m-------------------&c&l Statistiken &e&m-------------------'
  commandVerkaufSuccess: '&7Du hast &e%AMOUNT% %MATERIAL% &7fuer &a%MONEY% HCs &7verkauft'
  commandVerkaufSuccessLog: 'Verkauf: %PLAYER% hat %AMOUNT% %MATERIAL% fuer %MONEY% HCs verkauft'
  commandVerkaufNotInInv: '&cDu hast kein &e%MATERIAL% &cin deinem Inventar'
  commandVerkaufUsage: '&cVerwendung: &f/verkauf <beetroot|brownmushroom|cactus|carrot|cocoa|melon|netherwart|potato|pumpkin|redmushroom|sugarcane|wheat>'
  commandVoteGrabReward: '&7Hole dir deine Belohnung jetzt mit &e&o/vote getreward'
  commandVoteMessage: '&3Klicke folgenden Link zum Voten &e>>\n&6https://halfminer.de/voten.php?name=%PLAYER%'
  commandVoteMessageNotPlayer: '&3Klicke folgenden Link zum Voten &e>>\n&6https://halfminer.de/voten.php'
  commandVoteReached: '&2&l%TOTALVOTESTHRESHOLD% Votes erreicht! &7Event wird angekuendigt'
  commandVoteRewardDeny: '&cDu hast keine offene Belohnung'
  commandVoteRewardInvFull: '&cDein Inventar ist voll, bitte mache Platz und verwende das Kommando &e/vote getreward'
  commandVoteTop: '&e&m--------------------&c&l Voten &e&m--------------------'
  commandVoteUntil: '&7Votes bis zum naechsten Event: &d%TOTALVOTES%&7&o/2000'
  commandVoteVoted: '&e%PLAYER% hat eben mit &a/vote &egevotet'
  hanStorageSaveSuccessful: 'Die Daten wurden gespeichert'
  hanStorageSaveUnsuccessful: 'Die Daten konnten nicht gespeichert werden'
  hanTeleportBar: 'Teleport im Gange, bleibe still stehen...'
  hanTeleportDone: '&7Teleportiere...'
  hanTeleportMoved: '&cTeleport abgebrochen, du hast dich bewegt'
  hanTeleportPending: '&cDu hast bereits einen offenen Teleport, bitte warte'
  hanTeleportStart: '&7Bewege dich nicht, der Teleport startet in &a%TIME% &7Sekunden'
  modAntiKillfarmingBlockedBroadcast: '&e%KILLER% &cund &e%VICTIM% &cwurden wegen Killfarming temporaer vom PvP und verwenden von Kommandos ausgeschlossen'
  modAntiKillfarmingBlockedKiller: '&cZum Schutz vor Killfarming wurdest du fuer &a%TIME% &cMinuten vom PvP und verwenden von Kommandos ausgeschlossen, weil du &e%PLAYER% &czu haeufig getoetet hast. Weitere Infos: &a/regeln Killfarming'
  modAntiKillfarmingBlockedVictim: '&cZum Schutz vor Killfarming wurdest du fuer &a%TIME% &cMinuten vom PvP und verwenden von Kommandos ausgeschlossen, weil &e%PLAYER% &cdich zu haeufig getoetet hat. Weitere Infos: &a/regeln Killfarming'
  modAntiKillfarmingNoCommand: '&cKommandos sind fuer dich weitere &a%TIME% &cSekunden deaktiviert, da du Killfarming betrieben hast'
  modAntiKillfarmingNoPvPAttack: '&cZum Schutz vor Killfarming darfst du weitere &a%TIME% &cSekunden kein PvP betreiben'
  modAntiKillfarmingNoPvPProtect: '&6%PLAYER% ist zum Schutz vor Killfarming weitere &a%TIME% &cvom PvP ausgeschlossen'
  modAntiKillfarmingWarning: '&cAchtung! Killfarming ist gegen die Regeln. Das wiederholte toeten, bzw. toeten lassen desselben Spielers fuehrt zum Ausschluss vom PvP und dem verwenden von Kommandos'
  modAntiXrayInvalidMaterialLog: 'Das Material %MATERIAL% existiert nicht'
  modChatManGlobalmuteDenied: '&cDer Chat ist aktuell deaktiviert'
  modChatManGlobalmuteOff: '&eGlobale Stummschaltung deaktiviert'
  modChatManGlobalmuteOn: '&eGlobale Stummschaltung aktiv - Chat deaktiviert'
  modChatManMentioned: '&7Du wurdest von &a&l%PLAYER% &7im Chat erwähnt'
  modCombatLogBossBar: '&7Kampf mit &a&l%PLAYER% &7(Level: &a%LEVEL%&7) - &4%HEALTH%&f/&7%MAXHEALTH% &oLeben'
  modCombatLogCountdown: '&cIm Kampf: &e%TIME% &7Sekunden | &r%PROGRESSBAR%&r &7| Ausloggen: Tod'
  modCombatLogLoggedOut: '&e%PLAYER% &chat sich im Kampf ausgeloggt'
  modCombatLogNoArmorChange: '&cDu kannst im Kampf nicht deine Rüstung ausziehen'
  modCombatLogNoCommand: '&cDu kannst im Kampf keine Kommandos benutzen'
  modCombatLogNoEnderpearl: '&cDu kannst im Kampf keine Enderperlen benutzen'
  modCombatLogProgressSymbols: '-'
  modCombatLogUntagged: '&aDu bist nicht mehr im Kampf'
  modGlitchProtectionBedrock: '&cEventuelles Glitching durch &e%PLAYER%&c am Ort &e%LOCATION%'
  modGlitchProtectionNether: '&cDer Aufenthalt auf dem Netherdach ist verboten'
  modGlitchProtectionNetherNotify: '&c%PLAYER% war auf dem Netherdach bei &e%LOCATION%&c und wurde getoetet'
  modMotdLine: '&e&l<<<<<%COLOR%&l Two and a half Miner &e&l>>>>>\n&7%REPLACE%&7! (mc.halfminer.de)'
  modPerformanceReachedHopper: '&cEs sind bereits zu viele Hopper in deiner Umgebung'
  modPerformanceReachedHopperLog: '%PLAYER% hat das Limit (%LIMIT%) bei %LOCATION% erreicht'
  modPvPDeathStreak: '&c&l%PLAYER%&7 ist &c&l%STREAK% &7mal in Folge gekillt worden'
  modPvPKillStreak: '&a&l%PLAYER%&7 hat &c&l%STREAK% &7Kills in Folge'
  modRespawnFirstJoin: '&0&l>>>> &bWillkommen, &a&l%PLAYER%&b! &0&l<<<<'
  modRespawnForced: '&7Du wurdest von einem Serverteam-Mitglied zum Spawn teleportiert'
  modSignEditLinePasted: '&aSchild editiert'
  modSignEditSignCopied: '&7Schild kopiert, klicke auf das Schild, auf welches die Kopie angewandt werden soll'
  modSignEditSignPasted: '&aText eingefuegt, es verbleiben &e%AMOUNT% &aKopien'
  modSkillLevelDerank: '&cDein Skilllevel wurde reduziert, weil du seit 4 Tagen kein PvP mehr gemacht hast'
  modSkillLevelDerankTitle: ' \n&cDu wurdest degradiert: &7Level &a%SKILLLEVEL% &7(%SKILLGROUP%)'
  modSkillLevelLog: 'Skilllevel: %PLAYER% Level %SKILLOLD% -> %SKILLNEW% (%SKILLNO%)'
  modSkillLevelUprankTitle: ' \n&aDu wurdest befoerdert: &7Level &a%SKILLLEVEL% &7(%SKILLGROUP%)'
  modStaticListenersCommandSleep: '&cDu kannst keine Kommandos im Bett benutzen'
  modStatsDeath: '&cDu bist gestorben! &7Tode: &f%DEATHS%'
  modStatsDeathLog: 'Survival: %PLAYER% ist gestorben'
  modStatsNameChange: '&e%OLDNAME% &bhat den Namen zu &a%NEWNAME% &bgewechselt'
  modStatsPvPDeath: '&e%KILLER% &7hat dich eliminiert! Tode: &e%DEATHS% &7| K/D: &e%KDRATIO%'
  modStatsPvPKill: '&7Du hast &e%VICTIM% &7eliminiert! Kills: &e%KILLS% &7| K/D: &e%KDRATIO%'
  modStatsPvPLog: 'PvP: %KILLER% hat %VICTIM% eliminiert'
  modStatsRightClick: '&fSkillgruppe: &6%SKILLGROUP% &7| &fKills: &6%KILLS% &7| &fK/D: &6%KDRATIO%'
  modStatsRightClickExempt: '&fist ein Serverteammitglied und nimmt am Spiel nicht teil'
  modTitlesJoinFormat: '&7<<<< &6Halfminer&7 >>>>\n&7Kontostand: &a$%BALANCE%&f - &7Online: &a%PLAYERCOUNT% &7&oSpieler'
  modTitlesNewPlayerFormat: '&4Willkommen, %PLAYER%!\n&7Verwende &e&l/neutp &7zum starten!'
  modTitlesNewPlayerFormatBar: '&7Verwende &e&l/neutp &7zum starten!'
  modTitlesNewsFormat: '&lNeuigkeiten: &r%NEWS%'
  modTitlesTablist: '&6&lTwo and a half Miner&7\nKonto: &a%BALANCE% &7&oHCs%BOTTOM%&7Teamspeak: &fts.halfminer.de &7| Online: &a%PLAYERCOUNT% &7&oSpieler'
  modTpsServerUnstable: '&cDer Server ist instabil, die Tps betraegt lediglich &e%TPS%'